plugins:
  canned_replies_enabled:
    default: true
    client: true
  canned_replies_groups:
    default: ""
    type: list
  canned_replies_everyone_enabled:
    default: false
    client: true
  canned_replies_everyone_can_edit:
    default: false
    client: true
